import { Geist, Geist_Mono, Sono } from "next/font/google";
import "./globals.css";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sono = Sono({
  variable: "--font-sono",
  subsets: ["latin"],
  weight: ["200","300","400","500","600","700","800"], // pick what you need
  display: "swap",
});

export const metadata = {
  title: "Admin Journal",
  description: "Generated by create next app",
    icons: {
    icon: "/tree.svg",        // favicon
    shortcut: "/tree.svg",    // old Safari/Chrome “shortcut icon”
    apple: "/tree.svg",       // iOS home screen icon (PNG preferred, but SVG works in many cases)
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${sono.variable}`}>
        {children}
      </body>
    </html>
  );
}
